import type { PublicNote } from '@/types/browser';

export const MOCK_PUBLIC_NOTES: PublicNote[] = [
  {
    id: 'pub_001',
    title: '愛されたい欲求と距離感の反復',
    body: 'また同じことで不安になってる。相手にわかってほしいのに、近づきすぎると逃げられる感じがする。これはもうパターンなのかもしれない。',
    tags: ['恋愛', '不安', '反復', '欲求', '距離感'],
    topic: '恋愛',
    source: 'talk',
    createdAt: '2025-04-01T10:00:00Z',
    isPublic: true,
  },
  {
    id: 'pub_002',
    title: '仕事を続けたい気持ちと怖さの矛盾',
    body: '今の仕事を続けるのが苦しい。でもやめるのも怖い。どっちに動いても後悔しそうで、ずっとここに立ったまま。',
    tags: ['仕事', '不安', '矛盾', '保留'],
    topic: '仕事',
    source: 'zen',
    createdAt: '2025-04-02T14:30:00Z',
    isPublic: true,
  },
  {
    id: 'pub_003',
    title: 'わかってほしさが見えた瞬間',
    body: '本当はわかってほしいのかもしれない。言葉にしたら小さく見えるけど、ずっとそこにある気がする。',
    tags: ['人間関係', '孤独', '欲求', '本音'],
    topic: '人間関係',
    source: 'emi',
    createdAt: '2025-04-03T09:15:00Z',
    isPublic: true,
  },
  {
    id: 'pub_004',
    title: '停滞を壊したい気持ち',
    body: '何かを変えたい。今のままでいることへの違和感が積み重なってる。どこから手をつければいいかわからないけど、動かないのは嫌だ。',
    tags: ['創作', '停滞', '欲求', '挑戦'],
    source: 'manual',
    createdAt: '2025-04-04T16:00:00Z',
    isPublic: true,
  },
  {
    id: 'pub_005',
    title: 'また同じ不安に戻る',
    body: 'また同じところに来た。少し前に抜け出せた気がしたのに。でも今回は、戻ってきたことに気づいた分だけ、少し違うかもしれない。',
    tags: ['不安', '反復', '回避'],
    source: 'talk',
    createdAt: '2025-04-05T11:00:00Z',
    isPublic: true,
  },
  {
    id: 'pub_006',
    title: '疲れたけど休めない感覚',
    body: '体は疲れてるのに、休むと余計しんどくなる気がして休めない。何かをしていないと落ち着かない。',
    tags: ['体調', '疲れ', '不安', '生活'],
    topic: '生活',
    source: 'manual',
    createdAt: '2025-04-06T20:00:00Z',
    isPublic: true,
  },
  {
    id: 'pub_007',
    title: '初めて声に出して言えた',
    body: '今日、ずっと言えなかったことを言った。うまくは言えなかったけど、言えた。それだけで少し軽くなった。',
    tags: ['挑戦', '本音', '変化'],
    source: 'talk',
    createdAt: '2025-04-07T18:30:00Z',
    isPublic: true,
  },
  {
    id: 'pub_008',
    title: '感情に名前がついた瞬間',
    body: 'ずっと何かがモヤモヤしてた。それが「寂しさ」だとわかったとき、少し楽になった。名前がつくだけで、扱えるようになる。',
    tags: ['感情', '孤独', '気づき'],
    source: 'zen',
    createdAt: '2025-04-08T09:00:00Z',
    isPublic: true,
  },
];
